# Miniconda3Dockerfile
FROM  jadehh/miniconda3:amd64-4.9.2
# image 标签
MAINTAINER jadehh@live.com

RUN conda create -n python3.6.9 python=3.6.9 -y
RUN echo "source activate python3.6.9" >> /root/.bashrc

