# packing环境
FROM  jadehh/miniconda3:aarch64-4.9.2

## pip环境设置
RUN pip install pyclipper==1.3.0.post4
RUN pip install shapely==2.0rc3
RUN pip install pillow==8.2.0
RUN pip install av==10.0.0
RUN pip install tornado==4.5.1
RUN pip install scipy==1.5.4
RUN pip install spyne==2.13.16
RUN pip install requests==2.26.0
RUN pip install lxml==4.7.1
RUN pip install suds==1.1.2
RUN pip install https://ghproxy.com/https://github.com/jadehh/samples/releases/download/v1.0.2/acllite-1.0.2-py3-none-any.whl
RUN pip install https://ghproxy.com/https://github.com/jadehh/pythonTools/releases/download/OpencvToolsV1.2.0/opencv_tools-1.2.0-py3-none-any.whl
RUN pip install https://gh.ddlc.top/https://github.com/jadehh/pythonTools/releases/download/JadeV1.5.8/jade-1.5.8-py3-none-any.whl




