# packing环境
FROM  jadehh/miniconda3:aarch64-4.9.2


RUN pip install psutil==5.9.4
RUN pip install ruamel.yaml==0.17.21
RUN pip install scipy==1.5.4
RUN pip install absl-py==1.3.0
RUN pip install protobuf==3.20.1
RUN pip install six==1.16.0
RUN pip install wrapt==1.14.1
RUN pip install packaging==22.0
RUN pip install opt_einsum==3.3.0
RUN pip install gast==0.5.3
RUN pip install astunparse==1.6.3
RUN pip install termcolor==2.1.1
RUN pip install flatbuffers==22.12.6
RUN pip install h5py==3.7.0
RUN pip install lmdb==1.3.0
RUN pip install scikit-learn==1.0.2
RUN pip install networkx==2.6.3
RUN pip install onnx==1.13.0
RUN pip install ply==3.11
RUN pip install dill==0.3.6
RUN pip install pyclipper==1.3.0.post4
RUN pip install shapely==2.0rc3
RUN pip install pillow==8.2.0
RUN pip install tornado==4.5.1
RUN pip install scipy==1.5.4
RUN pip install spyne==2.13.16
RUN pip install requests==2.26.0
RUN pip install lxml==4.7.1
RUN pip install suds==1.1.2
RUN pip install https://ghproxy.com/https://github.com/jadehh/pythonTools/releases/download/OpencvToolsV1.2.0/opencv_tools-1.2.0-py3-none-any.whl
RUN pip install https://gh.ddlc.top/https://github.com/jadehh/pythonTools/releases/download/JadeV1.5.8/jade-1.5.8-py3-none-any.whl


